import { Link, useParams } from 'react-router-dom';
import { ReportActions } from '../components/reports/ReportActions';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { EmptyState, PageHeader } from '../components/ui/Cards';

export function ReportsPage() {
  const { runId = '' } = useParams();
  const projectId = localStorage.getItem('finverify_project_id') ?? '';
  const hasReport = !!projectId && !!runId && runId !== 'latest';

  return (
    <section className="space-y-6">
      <PageHeader eyebrow="Reports" title="Download reports" description="Download the generated accountant workbook or machine-readable JSON report." />
      {hasReport ? (
        <Card>
          <CardContent className="space-y-4 p-5">
            <div><div className="text-sm font-semibold text-slate-950">Comparison reports</div><p className="mt-1 text-sm text-slate-500">These files were generated by the latest comparison run.</p></div>
            <ReportActions projectId={projectId} runId={runId} />
          </CardContent>
        </Card>
      ) : (
        <EmptyState title="Run a comparison first." description="Excel and JSON report downloads are enabled after FinVerify completes a two-document comparison." action={<Button asChild><Link to="/compare">Compare documents</Link></Button>} />
      )}
    </section>
  );
}
