import type { ReactNode } from 'react';
import { CheckCircle2, Circle, Clock3, FileText, ShieldCheck } from 'lucide-react';
import { ProgressBar } from './Cards';
import { StatusBadge } from './Badge';
import { Card } from './card';

export function PipelineProgress({ active = 7 }: { active?: number }) { const stages = ['Upload', 'Extraction', 'Normalization', 'Validation', 'Rule Engine', 'Comparison', 'Confidence', 'Reporting']; return <Card className="p-4"><div className="mb-4 flex items-center justify-between"><div><div className="section-title">Verification pipeline</div><h3 className="text-sm font-semibold text-slate-950">Deterministic audit workflow</h3></div><StatusBadge status="completed" /></div><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-8">{stages.map((stage, index) => <div key={stage} className="rounded-md border border-slate-200 bg-slate-50 p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-slate-700">{stage}</span>{index <= active ? <CheckCircle2 size={16} className="text-emerald-600" /> : <Circle size={16} className="text-slate-300" />}</div><div className="text-[11px] text-slate-500">{index <= active ? 'Completed' : 'Queued'} - {((index + 1) * 0.4).toFixed(1)}s</div></div>)}</div></Card>; }
export function RiskScoreCard({ score }: { score: number }) { const tone = score >= 70 ? 'text-red-700' : score >= 35 ? 'text-amber-700' : 'text-emerald-700'; return <Card className="p-5"><div className="flex items-center justify-between"><div><div className="section-title">Average risk score</div><div className={'mt-2 text-3xl font-semibold ' + tone}>{score}</div></div><ShieldCheck className="text-slate-400" size={28} /></div><div className="mt-4"><ProgressBar value={score} /></div></Card>; }
export function ActivityList({ items }: { items: Array<{ title: string; meta: string; status?: string }> }) { return <Card className="divide-y divide-slate-100">{items.map((item) => <div key={item.title} className="flex items-center justify-between gap-4 p-4"><div className="flex items-center gap-3"><div className="rounded-md bg-slate-100 p-2"><Clock3 size={15} className="text-slate-500" /></div><div><div className="text-sm font-medium text-slate-900">{item.title}</div><div className="text-xs text-slate-500">{item.meta}</div></div></div><StatusBadge status={item.status || 'completed'} /></div>)}</Card>; }
export function ReportCard({ title, meta, action }: { title: string; meta: string; action?: ReactNode }) { return <Card className="flex items-center justify-between gap-4 p-4"><div className="flex items-center gap-3"><div className="rounded-md bg-blue-50 p-2 text-blue-700"><FileText size={18} /></div><div><div className="text-sm font-semibold text-slate-950">{title}</div><div className="text-xs text-slate-500">{meta}</div></div></div>{action}</Card>; }
