import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { cn } from '../../lib/utils';
export const Sheet = DialogPrimitive.Root;
export const SheetTrigger = DialogPrimitive.Trigger;
export const SheetClose = DialogPrimitive.Close;
export const SheetContent = ({ className, children, ...props }: DialogPrimitive.DialogContentProps) => <DialogPrimitive.Portal><DialogPrimitive.Overlay className='fixed inset-0 z-40 bg-slate-950/20' /><DialogPrimitive.Content className={cn('fixed right-0 top-0 z-50 h-full w-[440px] overflow-y-auto border-l border-slate-200 bg-white p-6 shadow-xl', className)} {...props}>{children}<DialogPrimitive.Close className='absolute right-4 top-4 rounded-md p-1 text-slate-500 hover:bg-slate-100'><X size={16} /></DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal>;
export const SheetHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => <div className={cn('space-y-1 pr-8', className)} {...props} />;
export const SheetTitle = DialogPrimitive.Title;
export const SheetDescription = DialogPrimitive.Description;
